# Pandas

## Pandas is used for data manipulation, analysis and cleaning. Python pandas is well suited for different kinds of data, such as: 

- Tabular data with heterogeneously-typed columns
- Ordered and unordered time series data
- Arbitrary matrix data with row & column labels
- Unlabelled data
- Any other form of observational or statistical data sets

## Pandas Operations

- Slicing
- Merging and Joining
- Concatenation
- changing the index
- changing the column headers
- Data Munging

# First we will see basic things to be done then go into many more things which are req

### Slicing

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Datasets/titanic.csv")

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [6]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [7]:
df.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

### Merging and Joining

In [9]:
# same values different indexes

import pandas as pd
 
df1= pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])
 
df2=pd.DataFrame({ "HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006,2007,2008])
 
merged= pd.merge(df1,df2)
 
merged

HPI  Int_Rate  IND_GDP
0   80         2       50
1   90         1       45
2   70         2       45
3   60         3       67

In [12]:
# different values 

df1 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])
 
df2 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006,2007,2008])
 
merged= pd.merge(df1,df2,on ="HPI")

merged

HPI  Int_Rate_x  IND_GDP_x  Int_Rate_y  IND_GDP_y
0   80           2         50           2         50
1   90           1         45           1         45
2   70           2         45           2         45
3   60           3         67           3         67

In [15]:
df1 = pd.DataFrame({"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2001, 2002,2003,2004])
 
df2 = pd.DataFrame({"Low_Tier_HPI":[50,45,67,34,53],"Unemployment":[1,3,5,6,7]}, index=[2001, 2003,2004,2004,2005])
 
joined= df1.join(df2)

joined2 = df2.join(df1)

joined,joined2

(      Int_Rate  IND_GDP  Low_Tier_HPI  Unemployment
 2001         2       50          50.0           1.0
 2002         1       45           NaN           NaN
 2003         2       45          45.0           3.0
 2004         3       67          67.0           5.0
 2004         3       67          34.0           6.0,
       Low_Tier_HPI  Unemployment  Int_Rate  IND_GDP
 2001            50             1       2.0     50.0
 2003            45             3       2.0     45.0
 2004            67             5       3.0     67.0
 2004            34             6       3.0     67.0
 2005            53             7       NaN      NaN)

# so <i> "merge" </i> is joining on columns where as <i> "join" </i> is joining on indices

 Analyze the output of merge and join
 
 merge - if all the values of columns is equal then only one name, else naming changes
 
 join - left join on indices, if the index is not there in right dataframe then NaN is placed at that location

### Concat

In [19]:
df1 = pd.DataFrame({"HPI":[80,90,70,60],"Int_Rate":[2,1,2,3], "IND_GDP":[50,45,45,67]}, index=[2002,2003,2001,2004])
 
df2 = pd.DataFrame({"HPI":[80,90,70,60],"In_Rate":[2,1,2,3],"IND_GDP":[50,45,45,67]}, index=[2005, 2006,2007,2008])
 
concat= pd.concat([df1,df2],sort=False)
 
concat

HPI  Int_Rate  IND_GDP  In_Rate
2002   80       2.0       50      NaN
2003   90       1.0       45      NaN
2001   70       2.0       45      NaN
2004   60       3.0       67      NaN
2005   80       NaN       50      2.0
2006   90       NaN       45      1.0
2007   70       NaN       45      2.0
2008   60       NaN       67      3.0

In [41]:
df= pd.DataFrame({"Day":[1,2,3,4], "Visitors":[200, 100,230,300], "Bounce_Rate":[20,45,60,10]}) 

df.index=df.Day

In [42]:
df.head()

Day  Visitors  Bounce_Rate
Day                            
1      1       200           20
2      2       100           45
3      3       230           60
4      4       300           10

# inplace means change in dataframe, if it is true dataframe gets changed and then df.set_index returns none, if it is false then dataframe doesn't get changed but the modified dataframe is returned

In [75]:
# or

df= pd.DataFrame({"Day":[1,2,3,4], "Visitors":[200, 100,230,300], "Bounce_Rate":[20,45,60,10]}) 

df2=df.set_index("Day",inplace=False) 
df2

Visitors  Bounce_Rate
Day                       
1         200           20
2         100           45
3         230           60
4         300           10

In [74]:
df.head()

Day  Visitors  Bounce_Rate
0    1       200           20
1    2       100           45
2    3       230           60
3    4       300           10

In [76]:
#or

df= pd.DataFrame({"Day":[1,2,3,4], "Visitors":[200, 100,230,300], "Bounce_Rate":[20,45,60,10]}) 

df.set_index("Day",drop=True)

Visitors  Bounce_Rate
Day                       
1         200           20
2         100           45
3         230           60
4         300           10

In [77]:
df.rename(columns={"Visitors":"Users"})

Day  Users  Bounce_Rate
0    1    200           20
1    2    100           45
2    3    230           60
3    4    300           10

In [78]:
df.head()

Day  Visitors  Bounce_Rate
0    1       200           20
1    2       100           45
2    3       230           60
3    4       300           10

# Data Munging
- In Data munging, you can convert a particular data into a different format. For example, if you have a .csv file, you can convert it into .html or any other data format as well.

In [80]:
import pandas as pd
 
country= pd.read_csv("C:/Datasets/titanic.csv",index_col=0)
 
country.to_html('edu.html')

# https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python|

## The DataFrame can contain data that is:
- a Pandas DataFrame
- a Pandas Series: a one-dimensional labeled array capable of holding any data type with axis labels or index. An example of a Series object is one column from a DataFrame.
- a NumPy ndarray, which can be a record or structured
- a two-dimensional ndarray
- dictionaries of one-dimensional ndarray’s, lists, dictionaries or Series.

Note the difference between np.ndarray and np.array() . The former is an actual data type, while the latter is a function to make arrays from other data structures.

In [119]:
# One Interesting example of numpy found.....

# A structured array
my_array = np.ones(3, dtype=([('foo', int), ('bar', float)]))
# i.e. if we want integer ones, access through foo and float ones are accessed through bar
# Print the structured array
print(my_array['foo'])

# A record array
my_array2 = my_array.view(np.recarray)
# Print the record array
print(my_array2.foo)

print(my_array)
print(my_array['bar'])

[1 1 1]
[1 1 1]
[(1, 1.) (1, 1.) (1, 1.)]
[1. 1. 1.]


In [122]:
# Creating DataFrame

data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])
                
pd.DataFrame(data=data[1:,1:],index=data[1:,0],columns=data[0,1:])

# important things are, "data, index, columns" are the main basic properties of dataframe

Col1 Col2
Row1    1    2
Row2    3    4

In [123]:
# shape and len 
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))

# Use the `shape` property
print(df.shape)

# Or use the `len()` function with the `index` property
print(len(df.index))

(2, 3)
2


You could also use df[0].count() to get to know more about the height of your DataFrame, but this will exclude the NaN values (if there are any). That is why calling .count() on your DataFrame is not always the better option.

But df.count() can be used to find the no of NaN values

In [128]:
df

0  1  2
0  1  2  3
1  4  5  6

In [126]:
df.count()

0    2
1    2
2    2
dtype: int64

In [127]:
df[0].count()

2

In [129]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [130]:
df.columns.values

array([0, 1, 2], dtype=int64)

In [131]:
df2

Visitors  Bounce_Rate
Day                       
1         200           20
2         100           45
3         230           60
4         300           10

In [132]:
df2.columns

Index(['Visitors', 'Bounce_Rate'], dtype='object')

In [133]:
df2.columns.values

array(['Visitors', 'Bounce_Rate'], dtype=object)

In [135]:
df2.loc[1]['Visitors'] # here row and column names

200

In [137]:
df2.loc[1][0] 

200

In [138]:
df2.iloc[0][0] # here indexes

200

In [139]:
df2.iloc[1][0]

100

In [140]:
df2.index=['a','b','c','d']

In [142]:
df2.loc['a'][0] 

200

In [143]:
df2.loc[0]['Visitors']

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [144]:
df2.loc[0][0]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

# so only columns can be accessed with indices in loc and rows with index names,
# where as in iloc, both must be accesed through indexes

In [151]:
# Using `at[]`
print(df2.at['a','Visitors'])
#print(df2)
# Using `iat[]`
print(df2.iat[0,0])

200
200


In [152]:
df

0  1  2
0  1  2  3
1  4  5  6

In [153]:
del df[0]

In [154]:
df

1  2
0  2  3
1  5  6

In [155]:
df.drop(0) 

1  2
1  5  6

In [156]:
df

1  2
0  2  3
1  5  6

## inplace, axis are important to perform actions
## more over parameters labels,axis=1 can be replaced by one parameter columns

### You can remove duplicate rows from your DataFrame by executing df.drop_duplicates(). You can also remove rows from your DataFrame, taking into account only the duplicate values that exist in one column.

In [157]:
df=pd.DataFrame({"name":["sudheer","kiran",'shiva','dharmi','sudheer'],"cg":[9,9.5,9.3,9.4,9.6]})
df.head()

name   cg
0  sudheer  9.0
1    kiran  9.5
2    shiva  9.3
3   dharmi  9.4
4  sudheer  9.6

In [158]:
df.drop_duplicates(["name"])

name   cg
0  sudheer  9.0
1    kiran  9.5
2    shiva  9.3
3   dharmi  9.4

In [159]:
df.drop_duplicates(["name"],keep="last")

name   cg
1    kiran  9.5
2    shiva  9.3
3   dharmi  9.4
4  sudheer  9.6

In [160]:
df.drop_duplicates(["name"],keep=False)

name   cg
1   kiran  9.5
2   shiva  9.3
3  dharmi  9.4

In [170]:
df=pd.concat([df,pd.DataFrame({"name":["darji"],"cg":[9.3]})],ignore_index=True)
df

name   cg
0  sudheer  9.0
1    kiran  9.5
2    shiva  9.3
3   dharmi  9.4
4  sudheer  9.6
5    darji  9.3
6    darji  9.3
7    darji  9.3

In [174]:
df.drop_duplicates(["cg"])

name   cg
0  sudheer  9.0
1    kiran  9.5
2    shiva  9.3
3   dharmi  9.4
4  sudheer  9.6

In [176]:
df.drop_duplicates(["name",'cg']) # both must be equal

name   cg
0  sudheer  9.0
1    kiran  9.5
2    shiva  9.3
3   dharmi  9.4
4  sudheer  9.6
5    darji  9.3

In [184]:
# Check out your DataFrame `df`
df=pd.DataFrame(np.arange(1,10).reshape(3,3),columns=["A","B","C"])

print(df)
# Define the new names of your columns
newcols = {
    'A': 'new_column_1', 
    'B': 'new_column_2', 
    'C': 'new_column_3'
}

# Use `rename()` to rename your columns
df.rename(columns=newcols, inplace=True)

print(df)

# Use `rename()` to your index
print(df.rename(index={1: 'a'}))

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
   new_column_1  new_column_2  new_column_3
0             1             2             3
1             4             5             6
2             7             8             9
   new_column_1  new_column_2  new_column_3
0             1             2             3
a             4             5             6
2             7             8             9


In [186]:
df=pd.DataFrame({"Student1":["OK"  ,"Perfect" ,"Acceptable"], "Student2":["Awful", "Awful", "Perfect"], "Student3":["Acceptable","OK","Poor"]})
df

Student1 Student2    Student3
0          OK    Awful  Acceptable
1     Perfect    Awful          OK
2  Acceptable  Perfect        Poor

In [187]:
# Replace the strings by numerical values (0-4)
print(df.replace(['Awful', 'Poor', 'OK', 'Acceptable', 'Perfect'], [0, 1, 2, 3, 4])) 

   Student1  Student2  Student3
0         2         0         3
1         4         0         2
2         3         4         1


In replace to activate regex mode, pass parameter regex=True